facebam:
  client:
    inbox: ${ZEEBE_CAMEL_FACEBAM_HOME}/client/_fs/inbox
  cloud:
    inbox: ${ZEEBE_CAMEL_FACEBAM_HOME}/cloud/_fs/inbox
  broker:
    inbox: ${ZEEBE_CAMEL_FACEBAM_HOME}/cloud/broker/_fs/inbox

spring:
  application:
    name: broker

