facebam:
  root: /Users/jangalinski/IdeaProjects/holunda/zeebe-camel-facebam
  client:
    fs: ${facebam.root}/client/_fs
    inbox: ${facebam.client.fs}/inbox
  cloud:
    fs: ${facebam.root}/cloud/_fs
    inbox: ${facebam.cloud.fs}/inbox
  broker:
    fs: ${facebam.root}/cloud/broker/_fs
    inbox: ${facebam.broker.fs}/inbox

spring:
  application:
    name: broker
