facebam:
  root: /Users/jangalinski/IdeaProjects/holunda/zeebe-camel-facebam
  watermarker:
    fs: ${facebam.root}/cloud/worker/watermarker/_fs
    inbox: ${facebam.watermarker.fs}/inbox
    work: ${facebam.watermarker.fs}/work

spring:
  application:
    name: watermarker-worker

camel:
  springboot:
    mainRunController: true