spring:
  application:
    name: watermarker-worker

facebam:
  worker:
    name: ${spring.application.name}
    inbox: ${ZEEBE_CAMEL_FACEBAM_HOME}/cloud/worker/watermarker/_fs/inbox
    work: ${ZEEBE_CAMEL_FACEBAM_HOME}/cloud/worker/watermarker/_fs/work

camel:
  springboot:
    mainRunController: true
