facebam:
  watermarker:
    fs: ${ZEEBE_CAMEL_FACEBAM_HOME}/cloud/worker/watermarker/_fs
    inbox: ${facebam.watermarker.fs}/inbox
    work: ${facebam.watermarker.fs}/work

spring:
  application:
    name: watermarker-worker

camel:
  springboot:
    mainRunController: true