facebam:
  root: /Users/jangalinski/IdeaProjects/holunda/zeebe-camel-facebam
  thumbnailer:
    fs: ${facebam.root}/cloud/worker/thumbnailer/_fs
    inbox: ${facebam.watermarker.fs}/inbox
    work: ${facebam.watermarker.fs}/work

spring:
  application:
    name: thumbnailer-worker

camel:
  springboot:
    mainRunController: true
