facebam:
  thumbnailer:
    inbox: ${ZEEBE_CAMEL_FACEBAM_HOME}/cloud/worker/thumbnailer/_fs/inbox
    work: ${ZEEBE_CAMEL_FACEBAM_HOME}/cloud/worker/thumbnailer/_fs/work

spring:
  application:
    name: thumbnailer-worker

camel:
  springboot:
    mainRunController: true
