facebam:
  root: /Users/jangalinski/IdeaProjects/holunda/zeebe-camel-facebam
  client:
    fs: ${facebam.root}/client/_fs
    inbox: ${facebam.client.fs}/inbox
    outbox: ${facebam.client.fs}/outbox
  cloud:
    fs: ${facebam.root}/cloud/_fs
    inbox: ${facebam.cloud.fs}/inbox
    outbox: ${facebam.cloud.fs}/outbox

spring:
  application:
    name: faceBam-client

# this keeps the application+camelContext running
camel:
  springboot:
    mainRunController: true
