facebam:
  client:
    fs: ${ZEEBE_CAMEL_FACEBAM_HOME}/client/_fs
    inbox: ${facebam.client.fs}/inbox
    outbox: ${facebam.client.fs}/outbox
  cloud:
    fs: ${ZEEBE_CAMEL_FACEBAM_HOME}/cloud/_fs
    inbox: ${facebam.cloud.fs}/inbox
    outbox: ${facebam.cloud.fs}/outbox
  google-mail:
    clientId: ${ZEEBE_CAMEL_GMAIL_CLIENT_ID}
    clientSecret: ${ZEEBE_CAMEL_GMAIL_CLIENT_SECRET}
    accessToken: ${ZEEBE_CAMEL_GMAIL_ACCESS_TOKEN}
    refreshToken: ${ZEEBE_CAMEL_GMAIL_REFRESH_TOKEN}
    userId: ${ZEEBE_CAMEL_GMAIL_USER_ID}


spring:
  application:
    name: faceBam-client

# this keeps the application+camelContext running
camel:
  springboot:
    mainRunController: true
