facebam:
  client:
    root: ${ZEEBE_CAMEL_FACEBAM_HOME}/_demo/client
    inbox: ${facebam.client.root}/inbox
    outbox: ${facebam.client.root}/outbox
  cloud:
    root: ${ZEEBE_CAMEL_FACEBAM_HOME}/_demo/cloud
    inbox: ${facebam.cloud.root}/inbox
    outbox: ${facebam.cloud.root}/outbox

spring:
  application:
    name: faceBam-client

# this keeps the application+camelContext running
camel:
  springboot:
    mainRunController: true
